# fly.toml app configuration file generated for todo-srv on 2024-01-02T15:00:37-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wiki-srv"
primary_region = "sjc"

[build]
  dockerfile = "./app.fly.dockerfile"

[env]
  APP_NAME = "wiki0"
  AUTH_SERVER="https://wiki-auth-srv.fly.dev"
  WIKI_SERVER="https://wiki0.app"
  TODO_SERVER="https://todo0.app"
  TODO_AUTH_SERVER="https://todo-auth-srv.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
