version: '3.8'

services:
  id-assertion-authz-node-example:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      # The line below speeds up slowness of running jest tests (see https://github.com/docker/for-mac/issues/1358).
      - /workspaces/id-assertion-authz-node-example/node_modules

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'avocado'
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
  redis:
    image: redis:latest
    restart: unless-stopped
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

volumes:
  mysqldata:
